# List of cities supported by OpenWeatherAPI and their names
CITY_LIST = [
    "London",
    "Paris",
    "New York",
    "Tokyo",
    "Berlin",
    "Sydney",
    "Rome",
    "Moscow",
    "Cairo",
    "Toronto",
    "Rio de Janeiro",
    "Mumbai",
    "Beijing",
    "Dubai",
    "Amsterdam",
    "Barcelona",
    "Bangkok",
    "Los Angeles",
    "Istanbul",
    "Singapore",
    "Vienna",
    "Athens",
    "Prague",
    "Stockholm",
    "Cape Town",
    "Havana",
    "Buenos Aires",
    "Zurich",
    "Seoul",
    "Mexico City",
    "Helsinki",
    "Dublin",
    "San Francisco",
    "Madrid",
    "Florence",
    "Lisbon",
    "Copenhagen",
    "Osaka",
    "Vancouver",
    "Edinburgh",
    "Kuala Lumpur",
    "Warsaw",
    "Budapest",
    "Marrakech",
    "Johannesburg",
    "Vienna",
    "Prague",
    "Toronto",
    "Zurich",
    "Stockholm",
    "Seoul",
    "São Paulo",
    "Shanghai"
]